name: Test extension

on:
  push:
    paths:
      - 'extension/**'
      - '.github/workflows/build.yml'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :extension:test
