name: Publish Spring Boot image for smoke tests

on:
  push:
    paths:
      - 'springboot-actuator-smoke-test/**'
      - '.github/workflows/build-smoke-tests.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        run: echo "TAG=$(date '+%Y%m%d').$GITHUB_RUN_ID" >> $GITHUB_ENV

      - name: Build Java 17 Docker image
        run: ./gradlew :springboot-actuator-smoke-test:jib -Ptag=${{ env.TAG }} -Djib.httpTimeout=120000 -Djib.console=plain
