name: Release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build jar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :extension:assemble

      - name: Upload agent to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: extension/build/libs/opentelemetry-javaagent.jar
          asset_name: opentelemetry-javaagent.jar
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release"
